# Generated by Django 5.0.1 on 2024-02-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=300)),
                ('upload_date', models.DateTimeField()),
                ('available', models.BooleanField()),
            ],
        ),
    ]
